### ISSUE TITLE
Separating validations for editing and creating?

### ISSUE THREAD

**Issue by JoaoCnh** [fluxxu/bookshelf-validator#1]
Is there any way I can have separate validations for Creating and Editing?

For example in edit mode I don't want to edit the password. Just the other fields.

So can I have the validation ignore the password?

**Comment by fluxxu** [comment]
You can use scenarios.
Example:

``` javascript
// default rules
model.addRules({
    'email': {validator:'notEmpty'}
}).
//This group executes only in 'onCreate' scenario
addRules({
    'password': {validator:'notEmpty'}
}, 'onCreate');


model.validate('onCreate'); //validate email and password
model.validate(); //validate email only
```

Or you can simply skip password validation when !model.isNew:

``` javascript
{
  'password': [
    function (value, ctx) {
       if (!this.isNew) {
         return ctx.yield();
       }
    },
    {validator:'notEmpty'}
  ]
}
```

Hope this is helpful. Thanks.

**Comment by JoaoCnh** [comment]
Yep. That helped a lot and it worked and I got different validations to work :)

Thanks
